services:
  api:
    image: node:24-alpine
    working_dir: /app
    ports:
      - "3000:3000"
    environment:
      AWS_REGION: us-east-1
      DYNAMODB_ENDPOINT: http://dynamodb:8000
      DYNAMODB_TABLE: users
      AWS_ACCESS_KEY_ID: local
      AWS_SECRET_ACCESS_KEY: local
    volumes:
      - ./:/app
      - /app/node_modules
    command: sh -lc "npm ci && npm run dev"
    depends_on:
      - dynamodb

  dynamodb:
    image: amazon/dynamodb-local
    container_name: dynamodb-local
    command: "-jar DynamoDBLocal.jar -sharedDb -inMemory"
    ports:
      - "8000:8000"